name: Build docker images on release

on:
  release:
    types: [created]

jobs:
  docker-build-push-prod:
    runs-on: ubuntu-latest
    environment: STAGING_ENVIRONMENT
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short=7 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: echo Short SHA
        run: echo $SHORT_SHA
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER}}
          username: ${{ secrets.EO_PROJ_DOCKER_USERNAME }}
          password: ${{ secrets.EO_PROJ_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-browser:cache
          cache-to: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-browser:cache,mode=max
          push: true
          tags: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-browser:${{ github.event.release.tag_name }}-staging
          build-args: |
            catalog_url=${{ secrets.STAC_BROWSER_CATALOG_URL }}
